#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EC.Droid.Resource", IsApplication=true)]

namespace EC.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::EC.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::EC.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_autorenew_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_check_black = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_collections_black = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_crop_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_done_black = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_fullscreen_black = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_reply_black_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_rotate_left_black = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_rotate_right_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int monoandroidsplash = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sync = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ticket1 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
